language: c
sudo: required
dist: trusty
script: bash -ex .travis-ci.sh
env:
  matrix:
    - OCAML_VERSION=4.01.0
    - OCAML_VERSION=4.02.3
    - OCAML_VERSION=4.03.0
    - OCAML_VERSION=4.03.0+flambda
